/*
 * Trabalhodesenvolvido para disciplina de ISS - 2016
 */
package visao;

import controller.EmprestimoController;
import controller.MaterialBibliograficoController;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.time.LocalDate;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.Artigo;
import modelo.Emprestimo;
import modelo.Livro;
import modelo.Periodico;
import modelo.Video;

/**
 *
 * @author Gabriel
 */
public class EmprestimoProcura extends javax.swing.JFrame {
    private int opcao;
    /**
     * Creates new form EmprestimoProcura
     */
    public EmprestimoProcura() {
        initComponents();
    }

    public EmprestimoProcura(int opcao) {
        this.opcao = opcao;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldIDUsuario = new javax.swing.JTextField();
        jButtonProcurar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ID do Material:");

        jLabel2.setText("ID do Usuário:");

        jButtonProcurar.setText("Procurar");
        jButtonProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcurarActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Preencha os respectivos campos abaixo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(jButtonProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(23, 23, 23))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldID)
                                .addComponent(jTextFieldIDUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))))
                    .addComponent(jLabel3))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldIDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcurarActionPerformed
        EmprestimoController emprestimoController = new EmprestimoController();
        MaterialBibliograficoController materialController = new MaterialBibliograficoController();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        
        Emprestimo emprestimo = new Emprestimo();
        List<Emprestimo> listaEmprestimo = emprestimoController.consultarEmprestimo(Integer.parseInt(jTextFieldID.getText()), Integer.parseInt(jTextFieldIDUsuario.getText()), emprestimo);
        if (listaEmprestimo.isEmpty()) {
            NaoEncontrado naoEncontrado = new NaoEncontrado();
            naoEncontrado.setVisible(true);
        } else {
            switch (opcao){
                case 0:
                    Emprestimo emp = listaEmprestimo.get(0);
                    emp.setEstado(false);
                    emprestimoController.enviarDevolucao(emp);

                    switch (emp.getTipoMaterial()) {
                        case 0:
                            Livro livro = new Livro();
                            List<Livro> listaLivro = materialController.consultarMaterialID(0, emp.getIdMaterial(), livro);

                            if (listaLivro.isEmpty()) {
                                NaoEncontrado naoEncontrado = new NaoEncontrado();
                                naoEncontrado.setVisible(true);
                            } else {
                                listaLivro.get(0).setQuantLocados(listaLivro.get(0).getQuantLocados() - 1);
                                materialController.editarLivro(listaLivro.get(0));
                            }
                            break;

                        case 1:
                            Artigo artigo = new Artigo();
                            List<Artigo> listaArtigo = materialController.consultarMaterialID(0, emp.getIdMaterial(), artigo);

                            if (listaArtigo.isEmpty()) {
                                NaoEncontrado naoEncontrado = new NaoEncontrado();
                                naoEncontrado.setVisible(true);
                            } else {
                                listaArtigo.get(0).setQuantLocados(listaArtigo.get(0).getQuantLocados() - 1);
                                materialController.editarArtigo(listaArtigo.get(0));
                            }
                            break;

                        case 2:
                            Periodico periodico = new Periodico();
                            List<Periodico> listaPeriodico = materialController.consultarMaterialID(0, emp.getIdMaterial(), periodico);

                            if (listaPeriodico.isEmpty()) {
                                NaoEncontrado naoEncontrado = new NaoEncontrado();
                                naoEncontrado.setVisible(true);
                            } else {
                                listaPeriodico.get(0).setQuantLocados(listaPeriodico.get(0).getQuantLocados() - 1);
                                materialController.editarPeriodico(listaPeriodico.get(0));
                            }
                            break;

                        case 3:
                            Video video = new Video();
                            List<Video> listaVideo = materialController.consultarMaterialID(0, emp.getIdMaterial(), video);

                            if (listaVideo.isEmpty()) {
                                NaoEncontrado naoEncontrado = new NaoEncontrado();
                                naoEncontrado.setVisible(true);
                            } else {
                                listaVideo.get(0).setQuantLocados(listaVideo.get(0).getQuantLocados() - 1);
                                materialController.editarVideo(listaVideo.get(0));
                            }
                            break;
                    }
                break;
                
                case 1:
                    Calendar novaData = Calendar.getInstance();
                    novaData.add(Calendar.DAY_OF_MONTH, 7);
                    listaEmprestimo.get(0).setDataDevolucao(novaData.getTime());
                    emprestimoController.enviarDevolucao(listaEmprestimo.get(0));
                break;
            }
        
            ConfirmaOperacao confirma = new ConfirmaOperacao();
            confirma.setVisible(true);
            dispose();    
        }
    }//GEN-LAST:event_jButtonProcurarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmprestimoProcura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmprestimoProcura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmprestimoProcura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmprestimoProcura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmprestimoProcura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonProcurar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldIDUsuario;
    // End of variables declaration//GEN-END:variables
}
